### ISSUE TITLE
RDF/JS Sink & Store interface support

### ISSUE THREAD

**Issue by gsvarovsky** [m-ld/m-ld-js#81]
`Sink` (& `Store`). Transaction boundaries for an import might need a bit of thought: you could have one transaction per quad, or one transaction per stream, or some batching. That would then drive what the app sees, via updates.

**Comment by gsvarovsky** [comment]
OK great! here is what I have in mind for triples: we could broadly augment [MeldState](https://js.m-ld.org/interfaces/meldstate.html) with the [RDF/JS Streams **Store** interface](http://rdf.js.org/stream-spec/#store-interface). That would allow you to asynchronously feed triples into m-ld.

One consideration: in m-ld, an individual call to `write` takes some json-rql representing multiple triple deletions and insertions, making a consistent atomic change according to relevant constraints. The stream-based Store interface doesn't have any such boundaries: you can add and remove individual triples anytime. We could have a transaction for each individual triple, and this might be okay in some cases, but in others it might represent an intermediate state between consistent ones. So I'd prefer to think up front about having some kind of coherent 'write' boundary.

A way would be to expose the `Store` interface only to a callback. So, for example, a 'write' might look like this:

```js
await state.writeRdf(async store => { /* make calls to the store here */ });
```

_Originally posted by @gsvarovsky in https://github.com/m-ld/m-ld-spec/discussions/117#discussioncomment-6861604_

**Comment by gsvarovsky** [comment]
Prior art:
- [IndexedGraph, a prepared statements/indexed API for RDF databases](https://lists.w3.org/Archives/Public/public-rdfjs/2013Oct/0040.html) – no replies
- [O-Team's SubscribableDataset](https://github.com/o-development/o-dataset-pack#subscribabledataset-1) – extension to sync Dataset interface
- https://github.com/comunica/comunica/issues/810 – open ticket

**Comment by gsvarovsky** [comment]
A problem with using `Store` as a temporary representation of the dataset:

The Store interface assumes a mutable state, to which operations are applied serially. So, if you `import` a stream of quads, you can then `remove` an intersecting stream, you expect the intersection to be absent in the final state.

In our proposed interface this would not be the case. The imported quads would be gathered into an array of inserts, and the removed quads gathered into an array of deletes. In a single m-ld update, inserts logically follow deletes, so the intersection would be present, not absent.

This could lead to some unpleasant surprises, because we are breaking the Store contract. (Although it's rather implicit anyway; and I'm not sure what is expected in a Store when imports and removals are actually concurrent.)

This leads me to think that "transaction" was the wrong word to use, because that implies a private state that can be serially mutated. Let's consider instead an "update", which is much more in line with [m-ld's updates](https://js.m-ld.org/interfaces/update.html), in turn inspired by a [SPARQL delete/insert](https://www.w3.org/TR/sparql11-update/#deleteInsert). This is the API I'm considering:

```typescript
/**
 * An RDF dataset representation that provides update semantics.
 * @category RDF/JS
 */
export interface UpdatableRdfDataset<State, Q extends BaseQuad = Quad> {
  /**
   * Performs an atomic update to the dataset. The deletes and inserts will be
   * committed in the resolved state.
   */
  updateRdf(operation: { deletes?: Iterable<Q>, inserts?: Iterable<Q> }): Promise<State>;
}
```

**Comment by danielbeeke** [comment]
I agree, that the last option is a much more stable interface.

**Comment by gsvarovsky** [comment]
That is implemented, with some simplification:

https://github.com/m-ld/m-ld-js/blob/d8472eb24ef9306ef5a2b33487aa014f50ceffb0/src/rdfjs-support.ts#L59-L75

However, there is one more thing to consider:

When an update is made, any [followers of the clone](https://js.m-ld.org/interfaces/meldclone.html#follow) receive the changes that were actually made, as [MeldUpdates](https://js.m-ld.org/interfaces/meldupdate.html). These updates are provided as JSON-LD. I think it would be better for RDF applications to receive Quads, probably even using the new `BaseDeleteInsert` interface (above).

I will have a think about how this should be designed.

**Comment by gsvarovsky** [comment]
I have added support for updates with Quads. In the end, it was just a matter of adding a `quads` member to the `GraphSubjects` class which is used in a [MeldUpdate](https://m-ld-js-git-rdf-update-gsvarovsky.vercel.app/interfaces/meldupdate.html) for the deletes and inserts. It looks quite easy to use, I have created a live-code demo in this branch:

https://m-ld-js-git-rdf-update-gsvarovsky.vercel.app/#using-the-rdfjs-api

**Comment by gsvarovsky** [comment]
I merged the branch because it also had the very useful enhancement to provide an async iterator for following a clone. Happy to keep evolving the RDF API though of course. 🚀
